### ISSUE TITLE
User can view profile

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the profile of an adoptable dog.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user will be presented with a card component that shows the dog's picture, name, breed, and distance from their location.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-13 at 5 55 35 PM](https://user-images.githubusercontent.com/106103291/190034917-95c63a88-e21f-4067-b1d8-c38a3de18251.png)

![Screen Shot 2022-09-13 at 5 56 19 PM](https://user-images.githubusercontent.com/106103291/190034950-a1337a91-f831-48d9-8520-f2e3a00543ce.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include script from DBDesigner.
- [x] Update `data.sql` to insert data for one dummy user.

### ☁️ Server Tasks

- [x]  Write server fetch request to PetfinderAPI to get data.
  - [x] POST request with my key and secret to get token.
  - [x] Make another fetch request with token to get adoptable dog data.
  - [x] Send data as json object to client
  - [x] Catch any errors.

### ⚡ Client Tasks

- [x] Create a component to show profile card with placeholder images and text on mobile view.
  - [x] Render Logo component (fixed).
  - [x] Render MobileNavBar (fixed).
  - [x] Render ProfileCard component.
- [x] Add any desktop components to render().
  - [x] Render DesktopNavBar (fixed).
  - [x] Render NOPE & LOVE buttons.
  - [x] Hide/show components depending on if mobile or desktop views.
- [x] Apply all necessary styling.
- [x] Store client key and secret in env.
- [x] Write client fetch request on componentDidMount() to server to handle fetch requests to PetfinderAPI.
- [x] Update state of component with relevant data.
- [x] Update component to re-render with pertinent data.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
